package main.java.ws.services;

import main.java.ws.models.IncomingDoc;
import main.java.ws.models.ObjectFactory;
import main.java.ws.models.ResultDoc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://localhost:8088/ServiceSoap/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ServiceSoap {

  /**
   * @param melding models.IncomingDoc
   * @return models.ResultDoc
   */
  @WebMethod(action = "http://localhost:8088/ServiceSoap/BerichtMelding", operationName = "BerichtMelding")
  @WebResult(name = "Antwoord", targetNamespace = "http://localhost:8088/ServiceSoap/")
  @RequestWrapper(localName = "BerichtMelding", targetNamespace = "http://localhost:8088/ServiceSoap/", className = "models.BerichtMelding", partName = "param")
  @ResponseWrapper(localName = "BerichtendienstAntwoord", targetNamespace = "http://localhost:8088/ServiceSoap/", className = "models.BerichtendienstAntwoord", partName = "param")
  ResultDoc berichtMelding(
      @WebParam(name = "Melding", targetNamespace = "http://localhost:8088/ServiceSoap/")
      IncomingDoc melding);

  /**
   * @param request models.baa.IncomingDoc
   * @return models.baa.ResultDoc
   */
  @WebMethod(action = "http://localhost:8088/ServiceSoap/CityAlertDataRequest", operationName = "CityAlertDataRequest")
  @WebResult(name = "Antwoord", targetNamespace = "http://localhost:8088/ServiceSoap/")
  @RequestWrapper(localName = "BerichtVraag", targetNamespace = "http://localhost:8088/ServiceSoap/", className = "models.baa.BerichtVraag", partName = "param")
  @ResponseWrapper(localName = "BerichtAntwoord", targetNamespace = "http://localhost:8088/ServiceSoap/", className = "models.baa.BerichtAntwoord", partName = "param")
  ResultDoc cityAlertDataRequest(
      @WebParam(name = "Request", targetNamespace = "http://localhost:8088/ServiceSoap/")
      IncomingDoc request);

}
