
package main.java.ws.models.baa;

import main.java.ws.services.ServiceSoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataRequest", targetNamespace = "http://localhost:8088/ServiceSoap/", wsdlLocation = "http://localhost:8088/ServiceSoap?wsdl")
public class DataRequest
    extends Service
{

    private final static URL DATAREQUEST_WSDL_LOCATION;
    private final static WebServiceException DATAREQUEST_EXCEPTION;
    private final static QName DATAREQUEST_QNAME = new QName("http://localhost:8088/ServiceSoap/", "DataRequest");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/ServiceSoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATAREQUEST_WSDL_LOCATION = url;
        DATAREQUEST_EXCEPTION = e;
    }

    public DataRequest() {
        super(__getWsdlLocation(), DATAREQUEST_QNAME);
    }

    public DataRequest(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATAREQUEST_QNAME, features);
    }

    public DataRequest(URL wsdlLocation) {
        super(wsdlLocation, DATAREQUEST_QNAME);
    }

    public DataRequest(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATAREQUEST_QNAME, features);
    }

    public DataRequest(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataRequest(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap() {
        return super.getPort(new QName("http://localhost:8088/ServiceSoap/", "ServiceSoap"), ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8088/ServiceSoap/", "ServiceSoap"), ServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATAREQUEST_EXCEPTION!= null) {
            throw DATAREQUEST_EXCEPTION;
        }
        return DATAREQUEST_WSDL_LOCATION;
    }

}
