package main.java.com.incentro.ws.services;

import main.java.com.incentro.ws.models.mk.IncomingDoc;
import main.java.com.incentro.ws.models.mk.ObjectFactory;
import main.java.com.incentro.ws.models.mk.ResultDoc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://localhost:8088/ServiceSoap/")
@SOAPBinding(style = Style.DOCUMENT, parameterStyle = ParameterStyle.WRAPPED)
@XmlSeeAlso({ ObjectFactory.class })
public interface ServiceSoap {

  /**
   * @param melding models.IncomingDoc
   * @return models.ResultDoc
   */
  @WebMethod(action = "http://localhost:8088/ServiceSoap/BerichtMelding", operationName = "BerichtMelding")
  @WebResult(name = "Antwoord", targetNamespace = "http://localhost:8088/ServiceSoap/")
  @RequestWrapper(localName = "BerichtMelding", targetNamespace = "http://localhost:8088/ServiceSoap/", className = "models.mk.BerichtMelding", partName = "parameter")
  @ResponseWrapper(localName = "BerichtendienstAntwoord", targetNamespace = "http://localhost:8088/ServiceSoap/", className = "models.mk.BerichtendienstAntwoord", partName = "parameter")
  ResultDoc berichtMelding(
      @WebParam(name = "Melding", targetNamespace = "http://localhost:8088/ServiceSoap/")
      IncomingDoc melding);

  /**
   * @param request models.baa.IncomingDoc
   * @return models.baa.ResultDoc
   */
  @WebMethod(action = "http://localhost:8088/ServiceSoap/CityAlertDataRequest", operationName = "CityAlertDataRequest")
  @WebResult(name = "Antwoord", targetNamespace = "http://localhost:8088/ServiceSoap/")
  @RequestWrapper(localName = "BerichtVraag", targetNamespace = "http://localhost:8088/ServiceSoap/", className = "models.baa.BerichtVraag", partName = "parameter")
  @ResponseWrapper(localName = "BerichtAntwoord", targetNamespace = "http://localhost:8088/ServiceSoap/", className = "models.baa.BerichtAntwoord", partName = "parameter")
  main.java.com.incentro.ws.models.baa.ResultDoc cityAlertDataRequest(
      @WebParam(name = "Request", targetNamespace = "http://localhost:8088/ServiceSoap/")
      main.java.com.incentro.ws.models.baa.IncomingDoc request);

}
